### ISSUE TITLE
Замечания по flipByte

### ISSUE THREAD

**Issue by alexey-malov** [Angaev/OOP#4]
```c++
int flipByte(const int &number)
```

- [x] используйте upperCamelCase

**Comment by alexey-malov** [comment]
- [ ] Программа должна зеркально отражать биты в байте

**Comment by alexey-malov** [comment]
- [ ] Использовать uint8_t в качестве типа входного и выходного

**Comment by alexey-malov** [comment]
- [ ] Использовать uint8_t в качестве типа входного и выходного

**Comment by alexey-malov** [comment]
Байт может принимать значения от 0 до 255. Если пользователь введёт число за пределами этого диапазона, надо сообщить ему об ошибке

**Comment by Angaev** [comment]
Не забыть привести тип uint8_t к int при выводе

**Comment by alexey-malov** [comment]
static_cast

**Comment by alexey-malov** [comment]
```c++
uint8_t FlipByte(const uint8_t &number)
```
- [ ] объекты следует передавать по константной ссылке, если функция не модифицирует их состояние.
Примитивные объекты передавать по константной ссылке выгоды нет, лучше по значению
